<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JUVN070" failures="0" tests="4" name="extent_reports.Extent_Reports" time="0.114" errors="1" timestamp="2024-03-07T09:55:01 CST" skipped="3">
  <testcase classname="extent_reports.Extent_Reports" name="noCommerceLoginTest" time="0.000">
    <skipped/>
  </testcase> <!-- noCommerceLoginTest -->
  <system-out/>
  <testcase classname="extent_reports.Extent_Reports" name="noCommerceTitleTest" time="0.000">
    <skipped/>
  </testcase> <!-- noCommerceTitleTest -->
  <system-out/>
  <testcase classname="extent_reports.Extent_Reports" name="setExtent" time="0.114">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentReports.attachReporter(com.aventstack.extentreports.ExtentReporter[])&quot; because &quot;this.extent&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.attachReporter(com.aventstack.extentreports.ExtentReporter[])" because "this.extent" is null
at extent_reports.Extent_Reports.setExtent(Extent_Reports.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setExtent -->
  <system-out/>
  <testcase classname="extent_reports.Extent_Reports" name="noCommerceLogoTest" time="0.000">
    <skipped/>
  </testcase> <!-- noCommerceLogoTest -->
  <system-out/>
</testsuite> <!-- extent_reports.Extent_Reports -->
